version: "3.8"

volumes:
  pg_data:
  minio_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  minio:
    image: minio/minio
    env_file: .env
    command: server /data
    volumes:
      - minio_data:/data

  media_private_api:
    build: ./media_private_api
    env_file: .env
    depends_on:
      - minio

  meme_public_api:
    build: ./meme_public_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - media_private_api