# Test your FastAPI endpoints

@base_url = http://0.0.0.0:8000

GET {{base_url}}/memes
Accept: application/json

###

@meme_id = 0

GET {{base_url}}/memes/{{meme_id}}/
Accept: application/json

###

@meme_id1 = 1

GET {{base_url}}/memes/{{meme_id1}}/
Accept: application/json

###

POST {{base_url}}/memes/

{
  "text": "Test1",
  "image": ""
}

